name: my_pesa

on:
  push:
    branches:
      - main

jobs:
  # Creates Issues from comments
  create_issues:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - name: TODO to Issue
        uses: alstr/todo-to-issue-action@v4.6.3
